uint8 lr       # left_or_right
float64 x_base
float64 y_base
float64 z_base
float64 roll_base
float64 pitch_base
float64 yaw_base
float64[5] x
float64[5] y
float64[5] z
float64[5] roll
float64[5] pitch
float64[5] yaw
---
float32[11] j_ang